### ISSUE TITLE
Possible idea

### ISSUE THREAD

**Issue by bmullan** [Ne00n/woodKubernetes#3]
I am a longtime LXC/LXD user.

I've used many different Mesh VPN solutions (vpncloud, nebula, wireguard etc)

All are relatively complex to configure or update which hinders adoption.

Recently, I found Hyprspace:

https://github.com/hyprspace/hyprspace

This is unique because ***you don't have to*** configure or add anything to the LXD Host.

Install Hyprspace in any/all LXD containers local or remote.

Edit each LXD container's /etc/hyprspace/hyprspace.yaml (see the GitHub README.md) and change the IP

(10.x.x.x, 172.16.x.x or 192.168.x.x)

In the ***PEER*** section of each YAML add the:

*ID & IP from the Hyprspace YAML of some local/remote LXD container's Hyprspace YAML you want "this" LXD Container to ***PEER*** with.*

In each YAML's ***peer*** section, add as many ***PEERS*** as you want.

Obviously, you could automate much of this configuration in lots of ways.
cloud-init, Ansible etc etc

When you execute the command to bring ***up*** each Container's Hyprspace Interface...

All LXD containers will connect using the Hyprspace IP *network* you assigned in each YAML.

Connection usually takes 20-60sec

Afterwards, ***each local/remote LXD Container will be directly interconnected in a fully encrypted MESH VPN***.

I've tested w LXD Host servers on Digital Ocean, Hetzner cloud in Germany & my local servers and ***performance is great*** and *config is stupid simple*.

Anyway wanted to fyi you in case it helps your project.

A closely similar project to Hyprspace architecturally (IPFS, DHT, libp2p) but which also has an API so it can be integrated is EDGEVPN:

https://github.com/mudler/edgevpn

Brian

**Comment by Ne00n** [comment]
Thanks, but I am currently not planning to continue this project, I don't have any use case for it.
I did a few test runs, it worked well, however, I don't have any HA applications as of right now that need that uptime.

I rather trust wireguard with the vpn stuff, already made tools for it but thanks, good to know that this stuff exists.
